// problem002 - Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89,... . By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

function sumOfEven(limit) {
    let term1 = 1, term2 = 2, nextterm = 0;
    let array = [term1, term2];
    let accumulator = 2;
    while (nextterm <= limit) {
        if (nextterm % 2 === 0) {
            accumulator += nextterm;
        }
        nextterm = term1 + term2;
        term1 = term2;
        term2 = nextterm;
    }
    return accumulator;
}
console.log(sumOfEven(4000000));